# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RandomKey',
        ),
    ]
